### NFL NEWS WEB REQUEST (NEWS API)
GET http://localhost:3000/nfl_news.json
### NBA NEWS WEB REQUEST (NEWS API)
GET http://localhost:3000/nba_news.json


### ROTOWIRE RSS FEED NFL
GET http://localhost:3000/rotowire_nfl_news
### ROTOWIRE RSS FEED NBA
GET http://localhost:3000/rotowire_nba_news
### ROTOWIRE RSS FEED FEATURED ARTICLES
GET http://localhost:3000/rotowire_news


### Fantasy Football Analytics RSS FEED
GET http://localhost:3000/ffa_news
### Dynasty Nerds RSS FEED 
GET http://localhost:3000/dynasty_nerds_news
### Sleeper U RSS FEED 
GET http://localhost:3000/sleeper_u_news
### Player Profiler RSS FEED
GET http://localhost:3000/player_profiler_news


### Hoops Hype NBA RSS FEED
GET http://localhost:3000/hoops_hype_news
### Hoop Doctors NBA RSS FEED
GET http://localhost:3000/hoop_doctors_news
### Basketball Insiders NBA RSS FEED
GET http://localhost:3000/basketball_insiders_news


### Filtered Tweets by Keywork Params
GET http://localhost:3000/filtered_keyword_tweets


### Filtered Tweets by Keywork Params #2
GET http://localhost:3000/filtered_keyword_2_tweets
### Filtered Tweets by Keywork Params #3
GET http://localhost:3000/filtered_keyword_3_tweets
### Filtered Tweets by Keywork Params #4
GET http://localhost:3000/filtered_keyword_4_tweets



### Live Stream Tweets
GET http://localhost:3000/live_stream_tweets

### API CALL for live stream .txt
GET http://localhost:3000/live_stream_echos

### DESTROY CONNECTION
GET http://localhost:3000/disconnect_live_stream_tweets.json